user nginx;
worker_processes auto;

events {
    worker_connections 2048;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    set_real_ip_from 0.0.0.0/0;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    log_format hng_json escape=json
      '{'
        '"source_ip":"$remote_addr",'
        '"timestamp":"$time_iso8601",'
        '"method":"$request_method",'
        '"path":"$uri",'
        '"status":$status,'
        '"response_size":$body_bytes_sent,'
        '"host":"$host",'
        '"user_agent":"$http_user_agent"'
      '}';

    access_log /var/log/nginx/hng-access.log hng_json;
    error_log /var/log/nginx/error.log warn;

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 1024M;

    upstream nextcloud_upstream {
        server nextcloud:80;
    }

    server {
        listen 80;
        server_name metrics.dziphomefix.com.ng;

        access_log /var/log/nginx/hng-access.log hng_json;

        location / {
            proxy_pass http://host.docker.internal:5050;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80 default_server;
        server_name _;

        access_log /var/log/nginx/hng-access.log hng_json;

        location / {
            proxy_pass http://nextcloud_upstream;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
